name = "MeshIO"
uuid = "7269a6da-0436-5bbc-96c2-40638cbb6118"
author = "Simon Danisch"
version = "0.4.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ColorTypes = "0.8, 0.9, 0.10"
FileIO = "1.2.4"
GeometryBasics = "0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
